# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mail-ru
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: mail-ru
#   labels:
#     # You should set the "kubernetes.io/service-name" label.
#     # Set its value to match the name of the Service
#     kubernetes.io/service-name: mail-ru
# subsets:
#   - addresses:
#       - ip: 217.69.139.202
#       - ip: 217.69.139.200
#       - ip: 94.100.180.200
#       - ip: 94.100.180.201
#     ports:
#       - port: 80
# ---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mail-ru-ep # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: mail-ru
addressType: IPv4
ports:
  - appProtocol: http
    protocol: TCP
    port: 8080
endpoints:
  - addresses:
      - "217.69.139.202"
      - "217.69.139.200"
      - "94.100.180.200"
      - "94.100.180.201"