apiVersion: v1
kind: Pod
metadata:
  name: empty
  namespace: default
  labels:
    app: empty
spec:
  initContainers:
    - name: contant
      image: alpine/curl
      args:
        - https://www.sheldonbrown.com/web_sample1.html
        - '-o'
        - /usr/share/nginx/html/index.html
      volumeMounts:
        - name: emptydir
          mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
      name:  http
    volumeMounts:
    - name: emptydir
      mountPath: /usr/share/nginx/html
  volumes:
    - name: emptydir
      emptyDir: {}
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: empty
  type: NodePort
  ports:
  - name: nginx
    protocol: TCP
    port: 8080
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30100