version: '3.3'
services:
  prometheus:
    image: prom/prometheus
    ports:
    - '9090:9090'
    volumes:
    - prometheus_data:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yaml
    command:
    - '--config.file=/etc/prometheus/prometheus.yaml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention=1d'
    networks:
      - monitornig

volumes:
  prometheus_data:

networks:
  monitornig: